version: "3.7"
services:
    www:
        build:
            context: ./
            dockerfile: Dockerfile
        ports: 
            - "80:80"
        volumes:
            - ./:/var/www
            - ./public:/var/www/html
        networks:
            laravel_prod_net:
                ipv4_address: 172.21.100.10
        depends_on:
            - db
    db:
        image: mysql
        ports: 
            - "3306:3306"
        command: --default-authentication-plugin=mysql_native_password
        environment:
            MYSQL_DATABASE: group4_laravel
            MYSQL_PASSWORD: test
            MYSQL_ROOT_PASSWORD: test 
        volumes:
            - ./dump:/docker-entrypoint-initdb.d
            - ./conf:/etc/mysql/conf.d
            - persistent:/var/lib/mysql
        networks:
            - default
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        links: 
            - db:db
        ports:
            - 8080:80
        environment:
            MYSQL_USER: root
            MYSQL_PASSWORD: test
            MYSQL_ROOT_PASSWORD: test 
volumes:
    persistent: